/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InboxIndexRouteImport } from './routes/inbox/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as InboxIdRouteRouteImport } from './routes/inbox/$id/route'
import { Route as AccountSettingsIndexRouteImport } from './routes/account/settings/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as InboxIdInboxIndexRouteImport } from './routes/inbox/$id/$inbox/index'
import { Route as InboxIdInboxMessageIdSourceRouteImport } from './routes/inbox/$id/$inbox/$messageId.source'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIndexRoute = InboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIdRouteRoute = InboxIdRouteRouteImport.update({
  id: '/inbox/$id',
  path: '/inbox/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsIndexRoute = AccountSettingsIndexRouteImport.update({
  id: '/account/settings/',
  path: '/account/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIdInboxIndexRoute = InboxIdInboxIndexRouteImport.update({
  id: '/$inbox/',
  path: '/$inbox/',
  getParentRoute: () => InboxIdRouteRoute,
} as any)
const InboxIdInboxMessageIdSourceRoute =
  InboxIdInboxMessageIdSourceRouteImport.update({
    id: '/$inbox/$messageId/source',
    path: '/$inbox/$messageId/source',
    getParentRoute: () => InboxIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inbox/$id': typeof InboxIdRouteRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/inbox/': typeof InboxIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/account/settings/': typeof AccountSettingsIndexRoute
  '/inbox/$id/$inbox/': typeof InboxIdInboxIndexRoute
  '/inbox/$id/$inbox/$messageId/source': typeof InboxIdInboxMessageIdSourceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inbox/$id': typeof InboxIdRouteRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/inbox': typeof InboxIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/account/settings': typeof AccountSettingsIndexRoute
  '/inbox/$id/$inbox': typeof InboxIdInboxIndexRoute
  '/inbox/$id/$inbox/$messageId/source': typeof InboxIdInboxMessageIdSourceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inbox/$id': typeof InboxIdRouteRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/inbox/': typeof InboxIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/account/settings/': typeof AccountSettingsIndexRoute
  '/inbox/$id/$inbox/': typeof InboxIdInboxIndexRoute
  '/inbox/$id/$inbox/$messageId/source': typeof InboxIdInboxMessageIdSourceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inbox/$id'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/inbox/'
    | '/api/auth/$'
    | '/account/settings/'
    | '/inbox/$id/$inbox/'
    | '/inbox/$id/$inbox/$messageId/source'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inbox/$id'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/inbox'
    | '/api/auth/$'
    | '/account/settings'
    | '/inbox/$id/$inbox'
    | '/inbox/$id/$inbox/$messageId/source'
  id:
    | '__root__'
    | '/'
    | '/inbox/$id'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/inbox/'
    | '/api/auth/$'
    | '/account/settings/'
    | '/inbox/$id/$inbox/'
    | '/inbox/$id/$inbox/$messageId/source'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InboxIdRouteRoute: typeof InboxIdRouteRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  InboxIndexRoute: typeof InboxIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  AccountSettingsIndexRoute: typeof AccountSettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/': {
      id: '/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof InboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/$id': {
      id: '/inbox/$id'
      path: '/inbox/$id'
      fullPath: '/inbox/$id'
      preLoaderRoute: typeof InboxIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings/': {
      id: '/account/settings/'
      path: '/account/settings'
      fullPath: '/account/settings/'
      preLoaderRoute: typeof AccountSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/$id/$inbox/': {
      id: '/inbox/$id/$inbox/'
      path: '/$inbox'
      fullPath: '/inbox/$id/$inbox/'
      preLoaderRoute: typeof InboxIdInboxIndexRouteImport
      parentRoute: typeof InboxIdRouteRoute
    }
    '/inbox/$id/$inbox/$messageId/source': {
      id: '/inbox/$id/$inbox/$messageId/source'
      path: '/$inbox/$messageId/source'
      fullPath: '/inbox/$id/$inbox/$messageId/source'
      preLoaderRoute: typeof InboxIdInboxMessageIdSourceRouteImport
      parentRoute: typeof InboxIdRouteRoute
    }
  }
}

interface InboxIdRouteRouteChildren {
  InboxIdInboxIndexRoute: typeof InboxIdInboxIndexRoute
  InboxIdInboxMessageIdSourceRoute: typeof InboxIdInboxMessageIdSourceRoute
}

const InboxIdRouteRouteChildren: InboxIdRouteRouteChildren = {
  InboxIdInboxIndexRoute: InboxIdInboxIndexRoute,
  InboxIdInboxMessageIdSourceRoute: InboxIdInboxMessageIdSourceRoute,
}

const InboxIdRouteRouteWithChildren = InboxIdRouteRoute._addFileChildren(
  InboxIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InboxIdRouteRoute: InboxIdRouteRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  InboxIndexRoute: InboxIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  AccountSettingsIndexRoute: AccountSettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
